### ISSUE TITLE
Possible Bug: While filtering centers with minimum age

### ISSUE THREAD

**Issue by sumit2k21** [bombardier-gif/covid-vaccine-booking#101]
Centers available in {location['pincode']} from : display 2 for Age given as 30; while both the centers in the given pin code have age limit as 45+.
So while displaying the logs the bot prints that centers are available in provided pincode with 18+ age limit while they are 45+ in on cowin website.

Its not filtering as expected. It is probably a bug someone can rectify this ? so we get correct info. on terminal.

**Comment by bombardier-gif** [comment]
Thanks Sumit. The filtering logic was merged yesterday here https://github.com/bombardier-gif/covid-vaccine-booking/pull/55
Do you see any flaw in the logic?

**Comment by sumit2k21** [comment]
Look on Cowin.gov.in website: at Pin 411033 there are 8 centers which have vaccine. For each center the Age criteria is 45+.
![image](https://user-images.githubusercontent.com/81756345/118033071-0113da80-b386-11eb-9792-88778f06a79e.png)
Now, while running the script. in the logs I see:
`Centers available in 411033 from 13-05-2021 as of 2021-05-13 01:01:24: 4`
![image](https://user-images.githubusercontent.com/81756345/118033689-bcd50a00-b386-11eb-82d9-e6d1b698e68a.png)
There are no centers which have vaccine and are serving 18+ people.
Only one beneficiary person is attached to this mobile number login whose age is 30, so they come into 18+ criteria only. So the filtering should just show 0 centers available not 4 because vaccine available for 45+ not suitable for added beneficiary so it should have filtered based on Age criteria. but its not working as expected I think. Anyone is open to test this case; provide a resolution.

**Comment by bombardier-gif** [comment]
@dap-123 can you please take a look at this?

**Comment by ayushanshul07** [comment]
@bombardier-gif Hi I have the fix for this issue. How can I create a PR? It shows me this error
➜  src git:(min_age_filter_fix) git push --set-upstream origin min_age_filter_fix
remote: Permission to bombardier-gif/covid-vaccine-booking.git denied to ayushanshul07.
fatal: unable to access 'https://github.com/bombardier-gif/covid-vaccine-booking.git/': The requested URL returned error: 403
➜  src git:(min_age_filter_fix) 

The fix is to iterate on the copy of list instead of original list and removing elements from within it.
Line 268 has fix, not the extra list(....) in for loop
![image](https://user-images.githubusercontent.com/13812647/118083646-e7ea4880-b3dc-11eb-9b9c-20ed7a96c1c0.png)

**Comment by bombardier-gif** [comment]
Thanks for the fix. One easy way is that, you could fork this repo, edit the code inline in the webapp, and then merge it back.

**Comment by ayushanshul07** [comment]
> Thanks for the fix. One easy way is that, you could fork this repo, edit the code inline in the webapp, and then merge it back.

Done!

**Comment by bombardier-gif** [comment]
Thanks for the fix @ayushanshul07 and @sumit2k21 Please test the latest changes and open an issue.

**Comment by dap-123** [comment]
Thanks @sumit2k21 for finding this bug and thanks @ayushanshul07 for the fix. 
Though it wouldn't have affected the actual slot booking for 18+, because it's already taken care in "_viable_options_" method in "_utils.py_". But I agree that it's imp and good that we show the correct number for available centers filtered by vaccine type and age :)
