### ISSUE TITLE
has someone explained how to use cowinotp retriever , i cant seem to find that particular issue. IFTTT is not working fine

### ISSUE THREAD

**Issue by devansh7777** [bombardier-gif/covid-vaccine-booking#107]

**Comment by ujaiswal** [comment]
Check the readme: https://github.com/bombardier-gif/covid-vaccine-booking#using-the-cowin-otp-retriever-android-app-1

**Comment by xxxAng** [comment]
@bombardier-gif  i would recommend you remove the instruction for cowinotp from read me, because it seems it send the SMS into a partcular KVdb bucket and its failing.
I think we wanted an alternate approach of using kvdc bucket but this is the same thing.

**Comment by devansh7777** [comment]
done! you may close this now.

**Comment by bombardier-gif** [comment]
I think @ujaiswal updated the code to change to the new kvdb url?

**Comment by bombardier-gif** [comment]
> I think we wanted an alternate approach of using kvdc bucket but this is the same thing.

What do you mean by this @xxxAng

**Comment by ujaiswal** [comment]
Yes, I did: https://github.com/bombardier-gif/covid-vaccine-booking/commit/9523caf20b887ccc0a4843819d40e485d455f565

**Comment by xxxAng** [comment]
@bombardier-gif His apk was pointing to old KVdb bucket.
I think the android app should have another text field to set customized bucket so that each time he does not need to have a new build.

My question is, how come this android approach is different because it sends the SMS to same KVdb bucket. 
So its basically the same using IFTTT app in mobile or using this new app.

No offense @ujaiswal , just want to understand the advantage of it.

**Comment by ujaiswal** [comment]
@xxxAng It already has the option of entering custom kvdb bucket key. The default is set to ASth4wnvVDPkg2bdjsiqMN which is online with the script which can be edited in the app itself.

**Comment by xxxAng** [comment]
Awesome then thanks @utkarsh
