### ISSUE TITLE
400 response code: Invalid security code

### ISSUE THREAD

**Issue by najmia** [bombardier-gif/covid-vaccine-booking#151]
![D53D7140-1DAE-46D7-9B1B-D25A46FE4F39](https://user-images.githubusercontent.com/56640566/118269655-4ab41080-b4bf-11eb-9630-740333933d0d.jpeg)
Hello. First of all thank you for this elegant solution. Works like a charm. Managed to get slots for two people already. I had a quick question. When I run it for 2 beneficiaries in parallel, I get a 400 response stating that the security code is invalid. Does this run successfully for multiple beneficiaries? Thank you for your help.

**Comment by bunduuk** [comment]
Yes it does, but I have tried for 2 different cities, and it worked like charm. Also the error is because the code entered is incorrect. Also since it checks via IP address I believe you are getting this because same IP address is asking 2 captcha for the same centers, at the same time. Try different IP address. Or delay the other one.

**Comment by bombardier-gif** [comment]
If you want to run in parallel. I would suggest you register them in 2 different mobile numbers and then try. I have heard of such parallel issues in the past too.
