### ISSUE TITLE
Error executing the script

### ISSUE THREAD

**Issue by bunny141** [bombardier-gif/covid-vaccine-booking#178]
syntax error on line number 47

**Comment by bombardier-gif** [comment]
can you please share more details about the error?

**Comment by akshay8043** [comment]
![image](https://user-images.githubusercontent.com/32493756/118391850-fdb57300-b653-11eb-95ad-7e8041d6a0ce.png)


I am also getting error while executing script.

Requirements was not installing because pythonpip3 was not installed after installing that, I tried with above command in picture but getting error.

can you please tell what pre-req i am missing?

**Comment by chetan1989-cloud** [comment]
I think install tkinter module, it says ModuleNotFoundError: No module named 'tkinter'

**Comment by shailesh** [comment]
> ![image](https://user-images.githubusercontent.com/32493756/118391931-6b619f00-b654-11eb-8fea-ae5e7afdf79f.png)
> 
> I am also getting error while executing script.
> 
> Requirements was not installing because pythonpip3 was not installed after installing that, I tried with above command in picture but getting error.
> 
> can you please tell what pre-req i am missing?

Try running using Python3 and if requirements are not fulfilled please pip install that in your virtual environment

**Comment by akshay8043** [comment]
> > ![image](https://user-images.githubusercontent.com/32493756/118391931-6b619f00-b654-11eb-8fea-ae5e7afdf79f.png)
> > I am also getting error while executing script.
> > Requirements was not installing because pythonpip3 was not installed after installing that, I tried with above command in picture but getting error.
> > can you please tell what pre-req i am missing?
> 
> Try running using Python3 and if requirements are not fulfilled please pip install that in your virtual environment

sudo pip3 install tkinter
The directory '/home/akshay/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/akshay/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tkinter
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/tkinter/

**Comment by shailesh** [comment]
@akshay8043 

sudo apt-get install python3-tk

**Comment by akshay8043** [comment]
> @akshay8043
> 
> sudo apt-get install python3-tk

This started the script in windows 10 (windows subsystem linux environment)

I want to know how this will automate OTP?

I had to manually type the OTP.

**Comment by shailesh** [comment]
> > @akshay8043
> > sudo apt-get install python3-tk
> 
> Thank you for the command.
> @shailesh
> 
> This started the script in windows 10 (windows subsystem linux environment)
> 
> I want to know how this will automate OTP and Booking?
> 
> I had to manually type the OTP.
> 
> How will I get captha?

Go through the readme https://github.com/bombardier-gif/covid-vaccine-booking#readme

**Comment by akshay8043** [comment]
> > > @akshay8043
> > > sudo apt-get install python3-tk
> > 
> > 
> > Thank you for the command.
> > @shailesh
> > This started the script in windows 10 (windows subsystem linux environment)
> > I want to know how this will automate OTP and Booking?
> > I had to manually type the OTP.
> > How will I get captha?
> 
> Go through the readme https://github.com/bombardier-gif/covid-vaccine-booking#readme

I am sorry I missed the part of auto or manual input of OTP that I found while re-running the script.

![image](https://user-images.githubusercontent.com/32493756/118393317-2e010f80-b65c-11eb-86fa-6fc94ad0f253.png)

Can anyone confirm how do I verify if Captcha will work on windows subsystem Linux or not?
Technically the code is running on Ubuntu Linux on TOP of windows 10 1909 with python3.

**Comment by akshay8043** [comment]
> > > @akshay8043
> > > sudo apt-get install python3-tk
> > 
> > 
> > Thank you for the command.
> > @shailesh
> > This started the script in windows 10 (windows subsystem linux environment)
> > I want to know how this will automate OTP and Booking?
> > I had to manually type the OTP.
> > How will I get captha?
> 
> Go through the readme https://github.com/bombardier-gif/covid-vaccine-booking#readme

![image](https://user-images.githubusercontent.com/32493756/118393436-c4cdcc00-b65c-11eb-9f69-85b751c398d7.png)

Thanks, I found the way of autoread OTP after I reran the script.

I have 2 questions:

Is this script directly books the slot? (Please answer as i nowhere see that it says that slot will be booked when running the script)

How will I get Captcha if i am not using Anti-captcha? how can i do captcha testing on my windows subsystem linux environment?

I am using windows subsystem linux environment on windows to avoid fresh installation of Ubuntu.

**Comment by akshay8043** [comment]
Received msg on telegram showing slots available but not getting captcha. (U45 thane group)
**This is what I think the issue is. I am not getting the captcha...!!!**

@bombardier-gif  do you think you can assist here?

x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
no display name and no $DISPLAY environment variable
Could not open /dev/tty0 or /dev/vc/0 for writing
open: No such file or directory
===================================================================================
Centers available in Thane from 16-05-2021 as of 2021-05-16 16:11:13: 2
Could not open /dev/tty0 or /dev/vc/0 for writing
open: No such file or directory
Could not open /dev/tty0 or /dev/vc/0 for writing
open: No such file or directory
+-------+-------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
|   idx | name                          | district   |   pincode |   available | date       | slots                                                                        |
+=======+===============================+============+===========+=============+============+==============================================================================+
|     1 | Apollo Hospital Modern School | Thane      |    400703 |           1 | 16-05-2021 | ['10:00AM-12:00PM', '12:00PM-02:00PM', '02:00PM-04:00PM', '04:00PM-05:00PM'] |
+-------+-------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
Random Rows.Column:1.2
============> Got Choice: Center #1, Slot #2
Booking with info: {'beneficiaries': ['79917609040900'], 'dose': 1, 'center_id': 697683, 'session_id': '70fd751b-29ac-4379-99db-09c2fbf644a0', 'slot': '12:00PM-02:00PM'}
================================= GETTING CAPTCHA ==================================================
Captcha Response Code: 200
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
no display name and no $DISPLAY environment variable
Could not open /dev/tty0 or /dev/vc/0 for writing
open: No such file or directory

**Comment by akshay8043** [comment]
> Received msg on telegram showing slots available but not getting captcha. (U45 thane group)
> **This is what I think the issue is. I am not getting the captcha...!!!**
> 
> @bombardier-gif do you think you can assist here?
> 
> ===================================================================================
> 
> # x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> no display name and no $DISPLAY environment variable
> Could not open /dev/tty0 or /dev/vc/0 for writing
> open: No such file or directory
> Centers available in Thane from 16-05-2021 as of 2021-05-16 16:11:13: 2
> Could not open /dev/tty0 or /dev/vc/0 for writing
> open: No such file or directory
> Could not open /dev/tty0 or /dev/vc/0 for writing
> open: No such file or directory
> +-------+-------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
> | idx | name | district | pincode | available | date | slots |
> +=======+===============================+============+===========+=============+============+==============================================================================+
> | 1 | Apollo Hospital Modern School | Thane | 400703 | 1 | 16-05-2021 | ['10:00AM-12:00PM', '12:00PM-02:00PM', '02:00PM-04:00PM', '04:00PM-05:00PM'] |
> +-------+-------------------------------+------------+-----------+-------------+------------+------------------------------------------------------------------------------+
> Random Rows.Column:1.2
> ============> Got Choice: Center #1, Slot #2
> Booking with info: {'beneficiaries': ['79917609040900'], 'dose': 1, 'center_id': 697683, 'session_id': '70fd751b-29ac-4379-99db-09c2fbf644a0', 'slot': '12:00PM-02:00PM'}
> ================================= GETTING CAPTCHA ==================================================
> Captcha Response Code: 200
> x_order_2: colinear!
> x_order_2: colinear!
> colinear!
> colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> colinear!
> colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> colinear!
> colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> colinear!
> colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> colinear!
> colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> x_order_2: colinear!
> colinear!
> colinear!
> x_order_2: colinear!
> no display name and no $DISPLAY environment variable
> Could not open /dev/tty0 or /dev/vc/0 for writing
> open: No such file or directory

I was not getting a captcha because of the windows subsystem for the Linux environment. 

I installed python on windows and run the app and seems like it is working ,

Thanks @bombardier-gif
