### ISSUE TITLE
Aarogya setu APIs info

### ISSUE THREAD

**Issue by chetan1989-cloud** [bombardier-gif/covid-vaccine-booking#198]
I see that Aarogya opens this application: https://web.swaraksha.gov.in/ncv19/cowin when it opens page asking for mobile number application and then it generates OTP using a call to: https://web.swaraksha.gov.in/api/v3/cowin/single/cowin_remote_generate_otp but this returns a http 404, may be because I was not logged in ?

I also checked when it is showing vaccine available slots (without login through OTP from Cowin): it searches using the same APIs (again may be because I was not logged in)
https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin?pincode=xxxxx&date=18-05-2021

Does it not require captcha because the header or origin tag has value https://web.swaraksha.gov.in?

Just throwing out info here, might be useful for you guys.

**Comment by shailesh** [comment]
In my guess swarakhsa is just routing back to COWIN APIs, acting as a wrapper. For Captcha as per my understanding they have an API keys to pass in Header and then that is handled via API keys if or else condition on the backend side. Need to deeg more into their backend code. since it is open source @chetan1989-cloud can you please look into this one. Thanks for the info

**Comment by shailesh** [comment]
this issue closes with Automated the boring captcha #253

**Comment by BumpyKnuckls** [comment]
+1
