### ISSUE TITLE
This Script does not show Correct Result

### ISSUE THREAD

**Issue by rajmishra78** [bombardier-gif/covid-vaccine-booking#235]
This Script is not able to show correct information from the CoWIN Portal. It displays the message -> No options are available right now. Next update will be in x seconds although there are many options available which had open slots when viewed through CoWIN Portal.
I think maybe it is because of the changes in the json format from the API call from the recent changes in the CoWIN Portal. Please look into it and make the corresponding changes,

**Comment by bombardier-gif** [comment]
There have always been some disrepancies in the data in script and the cowin portal, its due to the caching of data. read the first para of https://apisetu.gov.in/public/marketplace/api/cowin/cowin-public-v2
Let me know if you think that the script is not showing any slots available at-all

**Comment by swahareddy** [comment]
I believe in I am having the same problem. 
I have been running the script for 12+hrs, looking for Bangalore Urban and BBMP district in Karnataka
Cowin portal has many options, none shown in the script too.

I have also subscribed to some of the telegram update groups, and have seen 5-6 open slots coming there too since last night, but none of them came on the script

**Comment by shailesh** [comment]
check Cowin after login, since there is cache API without login, which they call public api. 
Also, join this telegram channel to understand the time for opening slots so that you do not hit unwanted APIs calls for fetching info

https://t.me/joinchat/Yc5M1kUeCKc2ZGY1

**Comment by shailesh** [comment]
I hope you were able to book one.

**Comment by swahareddy** [comment]
Yes I was. And I was able to help a few friends too. Thanks for the great
work :)
