### ISSUE TITLE
Add option for reschedule of appointments

### ISSUE THREAD

**Issue by dasanupam** [bombardier-gif/covid-vaccine-booking#255]
While the script runs at time some slots are booked which dont give vaccination and since we dont have any reschedule feature we are not able to do the booking again . Also the slot doesn't cancel manually once booked and the slot timing has passed.

**Comment by shailesh** [comment]
I would prefer manually canceling and then scheduling since there will be enough change in logic for this because rescheduling doesn't work straight forward. I the scheduled appointment is in an active session say today this can not be canceled until this is rescheduled for some other day and then canceled.

Doing manually is best otpions

**Comment by BumpyKnuckls** [comment]
+1 @shailesh Rescheduling logic is going to be complex and don't think at this time we intend to support it.
