### ISSUE TITLE
Appointments booked using Bot getting cancelled

### ISSUE THREAD

**Issue by ashwin-agarwal** [bombardier-gif/covid-vaccine-booking#257]
All appointments booked through the bot are getting cancelled in less than 5 mins. Noticed this three times.

**Comment by shailesh** [comment]
This is not an issue, this is where covid center are canceling and priorities for front line workers like medical staff, employees, ..... call 104 number to understand more. At least this is happening in Bangalore. They open the slot and then slots are canceled

**Comment by BumpyKnuckls** [comment]
Thanks a lot @shailesh for taking this one. +1. In cases where slots are cancelled, its most probably the case that either they are opened for testing only to realise that people have actually gone ahead and booked those slots or else they are prioritising it for other set of folks (like medical staff etc). 

In fact the first time that I got a slot and showed up at the centre only to realise that the centre was closed, I later realised that that slot was opened only for testing purposes. An hour after visiting the centre is when I received the cancellation sms.

So unfortunately at this time it looks like an issue at CoWIN's end rather than anything with the script. Would request to continue trying and I am pretty sure we will find a slot for you which helps with vaccination :)

**Comment by shailesh** [comment]
Try paid ones

**Comment by ashwin-agarwal** [comment]
All 3 times paid ones got cancelled.

**Comment by shailesh** [comment]
Try contacting covid helpline number or  The Cowin technical helpline: 0120 447 3222

This has nothing to do with the script. I've gone through the same thing.
