### ISSUE TITLE
[Open for Voting] Cycle between IPs to bypass rate limiter?

### ISSUE THREAD

**Issue by bombardier-gif** [bombardier-gif/covid-vaccine-booking#306]
Hi Team,

I am thinking of  a way to to change the IP address whenever the rate-limiting happens. We essentially change the IP address and send it in headers. 

Like this: https://infosecwriteups.com/bypassing-rate-limit-like-a-pro-5f3e40250d3c

Thoughts on this feature? 
[I am not sure if this will even work, but wanted to know your thoughts]

**Comment by bombardier-gif** [comment]
I will share a PR by EOD, Have the basic code in place,  I want to work on  the edge cases too

**Comment by uvmittal** [comment]
it wouldbe amazing

**Comment by shailesh** [comment]
Nice idea, today morning I was thinking bypass Tor to the entire system or at least the terminal. but this would get complicated so instead, some libraries out there would help in place

**Comment by shailesh** [comment]
I had this problem too. I tried the below steps and was able to run with refresh freq to 1 second.

**1. [download](https://www.torproject.org/download/download-easy.html.en) and install tor-browser
2. testing tor**

open terminal and type:

`curl --socks5-hostname localhost:9050 https://cdn-api.co-vin.in`

3. if you see the result it's worked.

Now we should test in python. Now run this code

```
import socks
import socket

#set socks5 proxy to use tor
socks.set_default_proxy(socks.SOCKS5, "localhost", 9050)
socket.socket = socks.socksocket
res = Request('https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByDistrict?district_id=294&date=24-05-2021', 
headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36',
 })
print(res.json())
```

I did this with Locust to make 1000 API calls for a 100 hatch rate and it worked for me.

```
Peak

No of concurrent Users-> 300
Hatch Rate-> 25
Target RPM-> 15000
Target RPS-> 115 RPS
Target Concurrency->
Post-Peak

No of concurrent Users-> 1000
Hatch Rate-> 100
Target RPM-> 15000
Target RPS-> 189 RPS
Target Concurrency->
```

**Comment by chetan1989-cloud** [comment]
Any updates on this guys?

**Comment by sanket-gupta** [comment]
There are two issues with using TOR
1. if everyone starts using TOR, the cowin system will get overwhelmed at some point of time. At the end, as responsible citizens, we need to allow the portal to keep running so that everybody can get vaccinated
2. . Cloudfront may already have the ability to block Tor Traffic. Refer to this https://stackoverflow.com/questions/55151477/website-is-blocking-me-accesing-from-tor

**Comment by jfreak27** [comment]
@shailesh have you limited tor to use India based IPs? 
When I'm doing that getting 403 from CloudFront. 
`curl -i --socks5-hostname localhost:9150 https://cdn-api.co-vin.in
HTTP/1.1 403 Forbidden`

**Comment by jfreak27** [comment]
@bombardier-gif were you able to bypass rate limiting by using IP forwarding headers? Not working for me. 
Event https://checkip.amazonaws.com/ shows same IP for all requests. 
I even tried using Anonymous Proxies as well. Looks like we will need Distorting proxy for IP to actually change.

**Comment by shailesh** [comment]
> There are two issues with using TOR
> 
> 1. if everyone starts using TOR, the cowin system will get overwhelmed at some point of time. At the end, as responsible citizens, we need to allow the portal to keep running so that everybody can get vaccinated
> 2. . Cloudfront may already have the ability to block Tor Traffic. Refer to this https://stackoverflow.com/questions/55151477/website-is-blocking-me-accesing-from-tor

Agree

**Comment by salian** [comment]
The rate limit is set quite low since the last few days. While manually booking through the website and repeatedly refreshing, I can barely stay logged-in for 60 seconds. And then I get blocked by cloudfront for the next 4 minutes. And if I don't refresh, slots get over in 2-3 seconds on average (I measured.) So time spent booking is wasted if we don't refresh around 60/s.

Especially in the context of Mumbai slots where slot timings are not announced beforehand and when they do get released everything gets over in approx 2.5 seconds, it becomes physically impossible to stay logged-in for even 5 minutes without getting blocked the next five minutes. If there are 50,000 people refreshing even for two hours throughout the day in Mumbai through the web front end, spending most of that time being blocked by the rate limiter instead of even actually making a booking request, this results in waste of 4000+ person-days. The short rate limit is a huge waste of national time.

This rate limit is set in the Cloudfront WAF, over and above the 15-minute OTP timeout. 

To avoid being rate limited, can we access the AWS instance behind the cloudfront WAF directly? 
Securitytrails.com and crt.sh may help find the AWS instance.

**Comment by shailesh** [comment]
@bombardier-gif any luck?

**Comment by bombardier-gif** [comment]
I will share the PR in couple of hours

**Comment by 6mxo89sqh** [comment]
@bombardier-gif Is manipulation of XFF header working? [AWS Documentations](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html) suggests it won't work by default. Are you trying some other way?

**Comment by shailesh** [comment]
```
# pip install torpy
from torpy.http.requests import TorRequests


def show_ip(resp):
    for line in resp.text.splitlines():
        if 'Your IP address appears to be' in line:
            print(line)


with TorRequests() as tor_requests:
    print("build circuit")
    with tor_requests.get_session() as sess:
        show_ip(sess.get("https://check.torproject.org/"))
        show_ip(sess.get("https://check.torproject.org/"))
    print("renew circuit")
    with tor_requests.get_session() as sess:
        show_ip(sess.get("https://check.torproject.org/"))
        show_ip(sess.get("https://check.torproject.org/"))
```

**This works to change the new IP everytime for a new request:**

```
build circuit
  <p>Your IP address appears to be:  <strong>199.249.230.78</strong></p>
  <p>Your IP address appears to be:  <strong>199.249.230.78</strong></p>
renew circuit
  <p>Your IP address appears to be:  <strong>89.163.143.8</strong></p>
  <p>Your IP address appears to be:  <strong>89.163.143.8</strong></p>

Process finished with exit code 0
```

**Comment by omkark96** [comment]
Also, I have observed the rate limit has been relaxed to a certain extent post the rigorous limit a couple of days back. I'm able to hit the APIs to check centers without errors for a considerably good amount of time.

**Comment by uvmittal** [comment]
> With [torpy](https://github.com/torpyorg/torpy) library you can renew new IP for every session of 99 API calls as you wish.
> 
> ```
> # pip install torpy
> from torpy.http.requests import TorRequests
> 
> 
> def show_ip(resp):
>     for line in resp.text.splitlines():
>         if 'Your IP address appears to be' in line:
>             print(line)
> 
> 
> with TorRequests() as tor_requests:
>     print("build circuit")
>     with tor_requests.get_session() as sess:
>         show_ip(sess.get("https://check.torproject.org/"))
>         show_ip(sess.get("https://check.torproject.org/"))
>     print("renew circuit")
>     with tor_requests.get_session() as sess:
>         show_ip(sess.get("https://check.torproject.org/"))
>         show_ip(sess.get("https://check.torproject.org/"))
> ```
> 
> **This works to change the new IP every time for a new request:**
> 
> ```
> build circuit
>   <p>Your IP address appears to be:  <strong>199.249.230.78</strong></p>
>   <p>Your IP address appears to be:  <strong>199.249.230.78</strong></p>
> renew circuit
>   <p>Your IP address appears to be:  <strong>89.163.143.8</strong></p>
>   <p>Your IP address appears to be:  <strong>89.163.143.8</strong></p>
> 
> Process finished with exit code 0
> ```

it works as said
but cowin still gets around it to block me

**Comment by uvmittal** [comment]
C:\Users\uvmit\Documents\GitHub\covid-vaccine-booking>python tor.py
build circuit
  <p>Your IP address appears to be:  <strong>213.164.206.XX3</strong></p>
  <p>Your IP address appears to be:  <strong>213.164.206.XX3</strong></p>
renew circuitx
  <p>Your IP address appears to be:  <strong>193.32.126.XX1</strong></p>
  <p>Your IP address appears to be:  <strong>193.32.126.XX1</strong></p>

C:\Users\uvmit\Documents\GitHub\covid-vaccine-booking>python src\covid-vaccine-slot-booking.py
Running Script
Enter the registered mobile number: XXXXXXXXXXXX

Do you want to enter OTP manually, instead of auto-read?
Remember selecting n would require some setup described in README (y/n Default n):
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/XXXXXXXXXXX
Requesting OTP with mobile number XXXXXXXXX..
Unable to Create OTP
{
 "error": "Too Many Requests"
}
clearing OTP bucket: https://kvdb.io/ASth4wnvVDPkg2bdjsiqMN/8XXXXXXX
Requesting OTP with mobile number 8XXXXXXX..
Unable to Create OTP
{
 "error": "Too Many Requests"
}

**Comment by SRvSaha** [comment]
@bombardier-gif @shailesh @6mxo89sqh Check this: https://www.mohfw.gov.in/pdf/CoWINAPIGuidelinesFinal240521.pdf
Things are getting really complicated now.

**Comment by 6mxo89sqh** [comment]
I have raised PR #432 for this. It is working. Please test and let me know your feedback.
@bombardier-gif @BumpyKnuckls

**Comment by shailesh** [comment]
@6mxo89sqh Thanks for the PR. Since the PR has a lot of other changes too, can you please make a separate independent PR for this feature.

**Comment by 6mxo89sqh** [comment]
> @6mxo89sqh Thanks for the PR. Since the PR has a lot of other changes too, can you please make a separate independent PR for this feature.

I will wait for the other PR to be merged. It is too time consuming to keep merging between multiple branches.

**Comment by 6mxo89sqh** [comment]
Raised #440

> @6mxo89sqh Thanks for the PR. Since the PR has a lot of other changes too, can you please make a separate independent PR for this feature.
