### ISSUE TITLE
Can we get Rid of secret in OTP calls

### ISSUE THREAD

**Issue by vaccine-warrior** [bombardier-gif/covid-vaccine-booking#335]
The documentation does not seem to ask for a secret

https://apisetu.gov.in/public/api/cowin#/User%20Authentication%20APIs/generateOTP

Why are we then sending a secret

The documented Endpoint as per the API Spec is
https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP

But the code currently uses the api endpoint from the cowin website which requires the secret 
 we should discuss which approach is better

**Comment by bombardier-gif** [comment]
I am ok as long as the OTP works fine. Is there a concern or any drawback in using the current implementation @vaccine-warrior ?

**Comment by vaccine-warrior** [comment]
Not an issue as such but the secret can act as an identifier and allow blocking of all scripts  that use that secret

**Comment by bombardier-gif** [comment]
Ok. lets keep this in mind in case our requests get blocked later

**Comment by sumit7** [comment]
@vaccine-warrior If we watch for network requests in browser while requesting otp and validating otp, we can see the secret being sent. It is different at different times. So we can pick up a different secret value from there. Not an elegant solution, since I have no idea what the secret variable is.
