### ISSUE TITLE
Please clarify the difference between pin code option and  State/District filter by Pincodes

### ISSUE THREAD

**Issue by YashMohanGarg** [bombardier-gif/covid-vaccine-booking#360]
Enter 1 for Pincode or 2 for State/District or 3 for State/District filter by Pincodes (Optimized for rate-limit) (Default 2): 1

**Comment by omkark96** [comment]
Option 3 fetches centers for the given district but will filter and check slots only for the pincodes that you provide. This helps because, in the case of option 1, you make separate calls for every pincode while in option 3 you just make one call to get all centres in the district and then filter locally to get relevant pincodes
