### ISSUE TITLE
Will your.exe program be closed after new guidelines from government?

### ISSUE THREAD

**Issue by hpk22** [bombardier-gif/covid-vaccine-booking#379]

**Comment by beastmaster-bit** [comment]
I think Govt will allow only registered third party apps to access apis going forwards. It will enable everyone in general public rather than IT skilled to book slots. Those unregistered may not be able to access thereafter

**Comment by bombardier-gif** [comment]
Once the APIs stop working, either we will see if there is a workaround or shut this down. 
These bots and scripts are developed in the first place because the CoWIN implementation is to un-usable, and keeps uneducated, non-tech savvy people out. 

I hope they also improve the system rather than playing cat and mouse with bot developers.
