### ISSUE TITLE
what can be done to reduce non detection of slots even pincodewise not working well

### ISSUE THREAD

**Issue by evioxtech** [bombardier-gif/covid-vaccine-booking#470]

**Comment by salian** [comment]
Slots are detected well. It just depends on the time interval between your requests. 

I suggest pick option 3 (by district), filter on a few pincodes, select only a single date by dd-mm-yy (instead of 7 days) and have a 5 second interval between queries. This also requires an OTP only every 15 mins.

If your luck is bad and the slots open 1 millisec after your first request and got over in the interim 5 seconds then bad luck, try again. 

But on average you will get ~2.5 seconds for the script to book which should be sufficient. 

If you really really want faster detection then host it on AWS. 

But the aim should be to just get the vaccine at any suitable place - don't get greedy only for a particular preference and hammer the API. Use it responsibly else it will just lead to more restrictions and cat-and-mouse games from the devs.

**Comment by evioxtech** [comment]
Thank you Salian for the input this is a good start

**Comment by shailesh** [comment]
Thanks, @salian for your comment!!
